name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    uses: sona1997/pt-terraform-github-actions/.github/workflows/reusable_terraform.yaml@main
    with:
      terraform_directory: "./terraform"
      terraform_version: "1.5.7"
      apply: true  # Set to false if you just want a plan
      destroy: false